const mergesort = require('./merge-sort')
const array = Array.from({ length: 100000 }, () => Math.floor(Math.random() * 10000))
const sortedArray = mergesort(array)
console.log(sortedArray)
console.log(sortedArray.length)
